---
- name: Converge
  hosts: all
  become: true
  vars:
    app_root: /opt/spondex
  pre_tasks:
    - name: Ensure application directory exists
      ansible.builtin.file:
        path: "{{ app_root }}/monitoring"
        state: directory
        mode: "0755"

    - name: Drop dummy monitoring script
      ansible.builtin.copy:
        dest: "{{ app_root }}/monitoring/monitor.py"
        mode: "0755"
        content: |
          #!/usr/bin/env python3
          print("noop")

    - name: Upload uv lockfile
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../../../../uv.lock"
        dest: "{{ app_root }}/uv.lock"
        mode: "0644"

    - name: Upload pyproject
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../../../../pyproject.toml"
        dest: "{{ app_root }}/pyproject.toml"
        mode: "0644"

  tasks:
    - name: Include monitoring role
      ansible.builtin.include_role:
        name: monitoring
