---
- name: Prepare
  hosts: all
  vars:
    ansible_remote_tmp: "/tmp/ansible-{{ lookup('env', 'USER') | default('ansible') }}"
  become: true
  tasks:
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
