
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - TZ=Europe/Moscow
      # Чувствительные токены подставляются Ansible-скриптом из GitHub Secret `APP_TOKENS` (см. tokens.env.example)
      - SPOTIPY_CLIENT_ID=${SPOTIPY_CLIENT_ID}
      - SPOTIPY_CLIENT_SECRET=${SPOTIPY_CLIENT_SECRET}
      - SPOTIPY_REDIRECT_URI=${SPOTIPY_REDIRECT_URI}
      - YANDEX_TOKEN=${YANDEX_TOKEN}
    volumes:
      - type: bind
        source: ./.cache
        target: /app/.cache
    ports:
      - "127.0.0.1:8888:8888"
    command:
      - --sync-playlists
      - --sync-favorite-albums
      - --sync-favorite-artists
      - --sleep
      - "300" 