# Example configuration for Spondex monitoring script
# Copy this file and tweak the thresholds/paths as needed. On hosts without
# Ansible you can edit /opt/spondex/monitoring/config.yaml directly; the next
# systemd run will pick up the changes. Ansible will only overwrite the live
# file when run with monitor_overwrite_config=true.

state_path: /var/lib/spondex-monitor/state.db
retention_days: 365
cpu_cores: null  # autodetect when null

# --- Thresholds ------------------------------------------------------------
load_window_minutes: 60
memory_threshold: 0.95

# --- Runtime ---------------------------------------------------------------
compose_file: /opt/spondex/docker-compose.prod.yml
docker_service: docker
app_checks:
  - container: spondex-app-1
    name: app
log_checks:
  - path: /opt/spondex/logs/app.log
    pattern: Traceback
  - path: /var/log/syslog
    pattern: Out of memory
  
db_check:
  container_name: spondex-postgres-1
  host: 127.0.0.1
  port: 5432
  user: postgres
  database: music_sync
  password_env_var: SPONDEX_DB_PASSWORD

disk_devices:
  - name: nvme0n1
    max_iops: 1000
    include_reads: true
    include_writes: true

notification:
  telegram:
    enabled: true
    chat_ids:
      - "8365606127"
    bot_token_env: TG_BOT_TOKEN
    subscriber_store: /var/lib/spondex-monitor/telegram_subscribers.json
    poll_updates: true
    api_base: https://api.telegram.org
    request_timeout: 10
  mail:
    enabled: false
    recipients:
      - ops@example.com
    sender: spondex-monitor@localhost
    subject_prefix: "[Spondex Monitor]"
    cc: []
