name: 'Setup Ansible Environment'
description: 'Sets up Python, uv, and Ansible tooling'

inputs:
  python-version:
    description: 'Python version to setup'
    required: false
    default: '3.13'
  extra-tools:
    description: 'Extra tools to install with uv tool'
    required: false
    default: ''

runs:
  using: 'composite'
  steps:
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
      shell: bash

    - name: Install Ansible tooling
      run: |
        uv tool install ansible
        if [ -n "${{ inputs.extra-tools }}" ]; then
          uv tool install ${{ inputs.extra-tools }}
        fi
      shell: bash