---
- name: Provision and deploy Spondex
  hosts: all
  become: true
  gather_facts: false

  vars:
    app_root: "/opt/spondex"
    deploy_app_port: "{{ (app_port | default('8888')) | int }}"
    repo_root: "{{ playbook_dir | dirname }}"
    local_app_tokens_path: "{{ repo_root }}/.env"
    local_spotify_cache_path: "{{ repo_root }}/.cache"
    is_ci_environment: "{{ (lookup('env', 'CI') | default('')) | length > 0 }}"
    ghcr_owner: "{{ ghcr_image_owner | default('sergeylavrentev') }}"
    ghcr_tag: "{{ ghcr_image_tag | default('latest') }}"
    registry_image: "ghcr.io/{{ ghcr_owner }}/spondex:{{ ghcr_tag }}"
    local_image_name: "spondex-local"
    local_image_tag: "latest"
    local_image_full: "{{ local_image_name }}:{{ local_image_tag }}"
    remote_image_archive: "/tmp/spondex-image.tar"
    deploy_image: "{{ local_image_full if not is_ci_environment else registry_image }}"
    python_major_minor: "3.13"
    python_binary_path: "/usr/bin/python{{ python_major_minor }}"
    python_apt_packages:
      - "python{{ python_major_minor }}"
      - "python{{ python_major_minor }}-venv"
    python_alternatives_priority: 213

  roles:
    - role: python_bootstrap
    - role: smoke_checks
    - role: system_bootstrap
    - role: application_sync
    - role: container_deploy
    - role: post_runtime
    - role: monitoring
