---
dependency:
  name: galaxy
  enabled: false

driver:
  name: docker

platforms:
  - name: debian12
    image: geerlingguy/docker-debian12-ansible:latest
    pre_build_image: true
    privileged: true
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    tmpfs:
      - /run
    environment:
      container: docker

provisioner:
  name: ansible
  env:
    ANSIBLE_CONFIG: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../ansible.cfg"
    ANSIBLE_COLLECTIONS_PATH: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../collections:/usr/share/ansible/collections"
    ANSIBLE_ROLES_PATH: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../"
    ANSIBLE_REMOTE_TEMP: /tmp/ansible
  config_options:
    defaults:
      roles_path: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') }}/../../../"
      remote_tmp: /tmp/ansible/ansible
  playbooks:
    prepare: prepare.yml
    converge: converge.yml
    verify: verify.yml

verifier:
  name: ansible
