---
- name: Prepare
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Debug /tmp permissions
      ansible.builtin.command: ls -la /tmp
      register: tmp_ls
    - name: Show /tmp permissions
      ansible.builtin.debug:
        msg: "{{ tmp_ls.stdout }}"
    - name: Ensure /tmp has correct permissions
      ansible.builtin.file:
        path: /tmp
        state: directory
        mode: '1777'
    - name: Ensure remote tmp directory exists
      ansible.builtin.file:
        path: /tmp/ansible
        state: directory
        mode: '1777'
    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: true
