name: Lint

on:
  workflow_call:
  workflow_dispatch:
  pull_request:
  push:
    branches-ignore:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      ANSIBLE_COLLECTIONS_PATH: ${{ github.workspace }}/ansible/collections:~/.ansible/collections:/usr/share/ansible/collections
      ANSIBLE_CONFIG: ansible/ansible.cfg
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ansible Environment
        uses: ./.github/actions/setup-ansible-env
        with:
          extra-tools: ansible-lint

      - name: Run Ansible lint
        run: ansible-lint -c ansible/ansible-lint.yml ansible/deploy.yml

      - name: Run Ansible syntax check
        run: ansible-playbook ansible/deploy.yml --syntax-check
