name: Molecule Tests

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'ansible/**'
  push:
    branches: [ main ]
    paths:
      - 'ansible/**'

jobs:
  molecule:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install dependencies in venv
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install molecule molecule-plugins[docker] ansible

      - name: Run Molecule
        continue-on-error: true
        env:
          ANSIBLE_COLLECTIONS_PATHS: "${{ runner.temp }}/ansible_collections:/usr/share/ansible/collections"
        run: |
          source .venv/bin/activate
          mkdir -p "${{ runner.temp }}/ansible_collections"
          cd ansible/roles/monitoring
          molecule test
