name: Post-deploy Verification

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  post_deploy:
    runs-on: ubuntu-latest
    env:
      DEPLOY_APP_TOKENS: ${{ secrets.APP_TOKENS }}
      DEPLOY_SPOTIFY_CACHE: ${{ secrets.SPOTIFY_CACHE_CONTENT }}
      DEPLOY_GHCR_PAT: ${{ secrets.GHCR_PAT }}
      DEPLOY_GHCR_USERNAME: ${{ secrets.DEPLOY_GHCR_USERNAME || github.repository_owner }}
      DEPLOY_TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN }}
      DEPLOY_APP_PORT: ${{ secrets.DEPLOY_APP_PORT }}
      DEPLOY_EXTRA_UFW_PORTS: ${{ secrets.DEPLOY_EXTRA_UFW_PORTS }}
      SSH_PORT: ${{ secrets.SSH_PORT || '49384' }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Ansible Environment
        uses: ./.github/actions/setup-ansible-env

      - name: Configure SSH
        env:
          SSH_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ env.SSH_PORT }}
        run: |
          set -euxo pipefail
          install -m 0700 -d ~/.ssh
          printf '%s' "$SSH_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -p "$SSH_PORT" "$SSH_HOST" >> ~/.ssh/known_hosts

      - name: Create dynamic inventory
        env:
          SSH_HOST: ${{ secrets.SSH_HOST }}
          SSH_PORT: ${{ env.SSH_PORT }}
        run: |
          set -euo pipefail
          if [ -z "$SSH_HOST" ]; then
            echo "SSH_HOST secret is required" >&2
            exit 1
          fi
          printf '[prod]\n%s ansible_port=%s\n' "$SSH_HOST" "$SSH_PORT" > /tmp/inventory.ini

      - name: Render extra vars
        run: |
          set -euxo pipefail
          python -c "import json, os, pathlib; payload={'app_tokens_content': os.environ.get('DEPLOY_APP_TOKENS',''), 'extra_ufw_ports': os.environ.get('DEPLOY_EXTRA_UFW_PORTS',''), 'app_port': os.environ.get('DEPLOY_APP_PORT',''), 'spotify_cache_content': os.environ.get('DEPLOY_SPOTIFY_CACHE',''), 'ghcr_username': os.environ.get('DEPLOY_GHCR_USERNAME',''), 'ghcr_pat': os.environ.get('DEPLOY_GHCR_PAT',''), 'monitor_telegram_bot_token': os.environ.get('DEPLOY_TG_BOT_TOKEN','')}; pathlib.Path('/tmp/extra_vars.json').write_text(json.dumps(payload))"

      - name: Run post-deploy checks
        env:
          SSH_USER: ${{ secrets.SSH_USER }}
        run: |
          set -euxo pipefail
          export ANSIBLE_HOST_KEY_CHECKING=true
          ansible-playbook ansible/post_deploy_checks.yml \
            -i /tmp/inventory.ini \
            --limit prod \
            -u "$SSH_USER" \
            --private-key ~/.ssh/deploy_key \
            --extra-vars '@/tmp/extra_vars.json'
